dehixorg/dehix_fastify

src/dao/freelancer.dao.ts, src/models/freelancer.entity.ts, src/types/v1/freelancer/freelancerRegistration.ts
experince field add in dao and model change  freelancer,freelancer body change
=> Aayush dao change

src/schema/v1/business/create.ts, src/schema/v1/business/delete.ts, src/schema/v1/business/get.ts, src/schema/v1/business/update.ts
Tushar 
Description: Create business schema
=> Tushar create business schema

src/dao/freelancer.dao.ts, src/schema/v1/freelancer/update.ts
Tushar 
Description: creating domain api and schema
=> create domain api and schema

src/constants/freelancer.constant.ts, src/controllers/freelancer.controller.ts, src/dao/freelancer.dao.ts, src/schema/v1/freelancer/update.ts, src/services/freelancer.service.ts, src/types/v1/freelancer/updateProfile.ts
Tushar 
Description: create interviews aligned api
=> create interviews aligned api

src/dao/freelancer.dao.ts, src/services/freelancer.service.ts
Tushar
Description: bud - [/freelancer/{freelancer_id}/project/{project_id}] check for both freelancer_id and project id and check for project id is align with freelancer_id if found then delete else not found 403 project_id
=> freelancer project delete bug resolve

src/controllers/freelancer.controller.ts, src/dao/freelancer.dao.ts, src/services/freelancer.service.ts
Tushar
Description: Bug fixed
/freelancer/{freelancer_id}
getting 500 error on giving wrong freelancer_id
getting 500 error on wrong id (it should be 404 not found)
first check for id if valid then update or 404 not found
/freelancer/{freelancer_id}/project
getting 500 on wrong id , it should be 404 not found
/freelancer/{freelancer_id}/interviews-aligned
getting 500 on wrong id , it should be 404 not found
/freelancer/{freelancer_id}/skill
getting 200 response but in response we don’t get data
=> Tushar bugs fix

src/controllers/business.controller.ts, src/dao/business.dao.ts, src/models/project.entity.ts, src/schema/v1/project/create.ts, src/services/business.service.ts
=> Aayush project api

src/common/constants.ts, src/controllers/bid.controller.ts, src/dao/bid.dao.ts, src/schema/v1/bid/update.ts, src/services/bid.service.ts, src/types/v1/bid/updateBid.ts
=> Aayush business bug fix

src/common/constants.ts, src/constants/freelancer.constant.ts, src/controllers/freelancer.controller.ts, src/models/business.entity.ts, src/services/freelancer.service.ts
=> Aayush all freelancer api

src/constants/freelancer.constant.ts, src/controllers/freelancer.controller.ts, src/dao/freelancer.dao.ts, src/models/freelancer.entity.ts, src/schema/v1/freelancer/create.ts, src/schema/v1/freelancer/delete.ts, src/schema/v1/freelancer/update.ts, src/services/freelancer.service.ts, src/types/v1/freelancer/delete.ts, src/types/v1/freelancer/updateProfile.ts
put and delete domain api for freelancer
=> Tushar domain api

src/constants/faq.constant.ts, src/controllers/faq.controller.ts, src/dao/faq.dao.ts, src/dao/index.ts, src/models/faq.entity.ts, src/models/index.ts, src/schema/v1/faq/create.ts, src/schema/v1/faq/delete.ts, src/schema/v1/faq/get.ts, src/services/faq.service.ts, src/services/index.ts, src/types/v1/faq/create.ts, src/types/v1/faq/delete.ts
=> Tushar faq Modal Schema and all apis

src/models/business.entity.ts, src/models/freelancer.entity.ts, src/schema/v1/business/create.ts, src/schema/v1/freelancer/create.ts, src/services/business.service.ts, src/services/freelancer.service.ts, src/types/v1/business/post.ts, src/types/v1/freelancer/create.ts
=> Aayush password remove

src/dao/freelancer.dao.ts, src/schema/v1/consultant/consultant.get.ts
Modified schema of "consultant,get.ts" file as it was not giving proper response.
=> Tested all consultant apis and fixed get consultant api.

src/constants/domain.constant.ts, src/constants/skills.constant.ts, src/controllers/domain.controller.ts, src/controllers/skills.controller.ts, src/dao/domain.dao.ts, src/dao/index.ts, src/dao/skills.dao.ts, src/models/domain.entity.ts, src/models/index.ts, src/models/skills.entity.ts, src/schema/v1/domain/domain.create.ts, src/schema/v1/domain/domain.delete.ts, src/schema/v1/skills/skills.create.ts, src/schema/v1/skills/skills.delete.ts, src/services/domain.service.ts, src/services/index.ts, src/services/skills.service.ts, src/types/v1/domain/createDomain.ts, src/types/v1/domain/deleteDomain.ts, src/types/v1/skills/createSkill.ts, src/types/v1/skills/deleteSkill.ts
- Added POST and DELETE apis in Domain and Skills
- Added bid is and bid_status in /bid/{project_id}/bids apis as per demand from frontend
=> Uttam changes in : domain, skill and bid apis

src/controllers/freelancer.controller.ts, src/dao/freelancer.dao.ts, src/services/freelancer.service.ts
add verification function in skills and domain
=> Tushar skill verification

src/controllers/freelancer.controller.ts, src/dao/freelancer.dao.ts, src/models/bid.entity.ts, src/services/freelancer.service.ts
Added verification for project and experience for freelancer
=> Uttam project-experience verifications

src/constants/projectDomain.constant.ts, src/controllers/projectDomain.controller.ts, src/dao/index.ts, src/dao/projectDomain.dao.ts, src/models/index.ts, src/models/projectDomain.entity.ts, src/schema/v1/projectDomain/projectDomain.create.ts, src/schema/v1/projectDomain/projectDomain.delete.ts, src/schema/v1/projectDomain/projectDomain.get.ts, src/services/index.ts, src/services/projectDomain.service.ts, src/types/v1/projectDomain/createProjectDomain.ts, src/types/v1/projectDomain/deleteProjectDomain.ts
schema, modal & crud operation for project domain
=> Tushar project domain

src/dao/freelancer.dao.ts, src/dao/verifications.dao.ts, src/services/verifications.service.ts, src/types/v1/verifications/getDocType.ts
=> made changes in verification get api

src/dao/verifications.dao.ts, src/models/verifications.entity.ts, src/services/business.service.ts, src/services/verifications.service.ts
verify business profile/ assign oracle
=> Tushar verify business

src/constants/bid.constant.ts, src/controllers/bid.controller.ts, src/dao/bid.dao.ts, src/schema/v1/bid/bid.get.ts, src/services/bid.service.ts
=> create getAllBids api

src/constants/freelancer.constant.ts, src/controllers/freelancer.controller.ts, src/dao/freelancer.dao.ts, src/schema/v1/freelancer/freelancer.get.ts, src/services/freelancer.service.ts
=> getAllDehixtalent api for admin

src/dao/business.dao.ts
Remove completed project form freelancer market place
=> Remove_completed_project_from_freelancer_market_place

src/models/projectDomain.entity.ts
Added createdBy createdAt in projectdomain.entity
=> Harshit/db-20/Added createdBy and createdAt in project domain

src/constants/interview.constant.ts, src/controllers/interview.controller.ts, src/dao/interview.dao.ts, src/models/interview.entity.ts, src/schema/v1/interview/interview.get.ts, src/services/interview.service.ts, src/types/v1/interview/getInterview.ts
Api's to seperate completed and current interviews for interviewee
=> Make interview workflow complete and test in end to end

src/controllers/business.controller.ts, src/dao/business.dao.ts, src/schema/v1/project/project.get.ts, src/services/business.service.ts
add projectDomain querySelector in getAllProjects api
=> add projectDomain querySelector in getAllProjects

src/constants/freelancer.constant.ts, src/controllers/admin.controller.ts, src/controllers/freelancer.controller.ts, src/controllers/projectDomain.controller.ts, src/controllers/verifications.controller.ts, src/dao/verifications.dao.ts, src/schema/v1/verifications/verifications.get.ts, src/services/verifications.service.ts, src/types/v1/verifications/getDocType.ts
create getAllVerification data for admin table & fix getAllverificationDataById
=> Tushar/db 22/oracle verification

eb/package.json, src/common/constants.ts, src/common/crud.service.ts, src/common/errors.ts, src/common/utils.ts
Added comments in common folder in constants, crud.service, errors, utils
=> Added comments in common

eb/package.json, src/common/auth.controller.ts, src/common/base.controller.ts, src/common/base.dao.ts, src/common/base.service.ts
Added comments in common folder to auth.controller, base.controller, base,dao, base.service.
=> Added comments to files in common

src/constants/admin.constant.ts, src/constants/bid.constant.ts, src/constants/business.constant.ts, src/constants/domain.constant.ts, src/constants/faq.constant.ts, src/constants/freelancer.constant.ts
Added comments to constants in admin, bid, business, domain, faq, freelancer
=> Added comments to constants

src/constants/hireDehixTalent.constant.ts, src/constants/interview.constant.ts, src/constants/notification.constant.ts, src/constants/projectDomain.constant.ts, src/constants/skills.constant.ts
Added comments to constants in hireDehixTalent, interview, notification, projectDomain, skiils
=> Added comments to constants/2

src/controllers/admin.controller.ts, src/controllers/bid.controller.ts, src/controllers/business.controller.ts, src/controllers/domain.controller.ts, src/controllers/faq.controller.ts
added comments to controllers in admin, bid, business, domain, faq
=> Harshit/add comments to controllers/1

src/schema/v1/project/project.create.ts, src/types/v1/project/postProject.ts
- The POST api of creating business project is not creating profile properly, so it is causing server  error in PUT api.
- So I modified schema to solve tis issue.
=> Uttam/df-94/bug fix - fixed bug in schema for Business profile is not working properly

src/constants/freelancer.constant.ts, src/controllers/freelancer.controller.ts, src/schema/v1/freelancer/freelancer.get.ts
Created get api for freelancer profile details except personal information
=> Added new api to get freelancer details for profile view

src/constants/freelancer.constant.ts, src/controllers/freelancer.controller.ts, src/dao/freelancer.dao.ts, src/schema/v1/freelancer/freelancer.get.ts, src/services/freelancer.service.ts
get api for education of freelancer
=> Harahit/db 30/create api for education

src/dao/verifications.dao.ts, src/services/verifications.service.ts, src/types/v1/verifications/getDocType.ts
fixed verification api to fetch data for undefined value
=> resolved error in verification api to get data for undefined value

src/controllers/bid.controller.ts, src/dao/bid.dao.ts, src/schema/v1/bid/bid.get.ts
=> fix getBidByFreelancerId api

src/constants/faq.constant.ts, src/controllers/faq.controller.ts, src/dao/faq.dao.ts, src/schema/v1/faq/faq.update.ts, src/services/faq.service.ts, src/types/v1/faq/updateFaq.ts
created put api to update status of faq
=> Harshit/db 34/api to update status of faq

src/schema/v1/bid/bid.get.ts
added description in all get api's of bid
=> Harshit/db 36/add description in bid

src/models/business.entity.ts, src/models/freelancer.entity.ts, src/schema/v1/business/business.create.ts, src/schema/v1/business/business.update.ts, src/schema/v1/freelancer/freelancer.create.ts, src/schema/v1/freelancer/freelancer.get.ts, src/schema/v1/freelancer/freelancer.update.ts, src/types/v1/business/postBusiness.ts, src/types/v1/business/updateBusiness.ts, src/types/v1/freelancer/createFreelancer.ts, src/types/v1/freelancer/updateProfile.ts
add profilePic type string in both freelancer and business and also update all swagger schema
=> Tushar/add profile pic field (ticket no - DB-41) 

src/dao/bid.dao.ts, src/dao/business.dao.ts, src/services/freelancer.service.ts
create api for get project for freelancer using querySelector
=> create api to get freelancer projects project with status (Ticket no: DF-152)

src/dao/freelancer.dao.ts
add freelancer_id, username and profilePic in dehix talent get api response
=> add some fileds in dehix talent get api response (ticket id: 28)

src/dao/freelancer.dao.ts
Adding freelancer_id in get API of freelancer dehix talent
=> Vansh/39/Add freelancer_id in get API of freelancer dehix talent

src/dao/business.dao.ts
remove default value of page & limit pass in argument of getProject api for freelancer marketplace
=> remove default page and limit value

src/schema/v1/freelancer/freelancer.get.ts
Added referral in get api of freelancer profile-info
=> Harshit/SP- 64/add referral in profile info api of freelancer

src/models/project.entity.ts
=> Harshit sharma/SP3 74/add profile id in projects

src/constants/freelancer.constant.ts, src/controllers/freelancer.controller.ts, src/dao/freelancer.dao.ts, src/models/freelancer.entity.ts, src/schema/v1/freelancer/freelancer.update.ts, src/services/freelancer.service.ts, src/types/v1/freelancer/UpdateFreelancer.ts
added the status for freelancer
=> Harshit Sharma/sp3 72/add status for freelancer

src/controllers/bid.controller.ts, src/controllers/hireDehixTalent.controller.ts, src/controllers/interview.controller.ts, src/controllers/ticket.controller.ts, src/controllers/transaction.controller.ts, src/controllers/verifications.controller.ts, src/models/userNotification.entity.ts
implemented the logic of notification in backend
=> Harshit sharma/sp3 100/notification implementation
